AWSTemplateFormatVersion: '2010-09-09'

Description: >
  !! This stack may incur (small) costs !!
  !! Default instance is t3.nano (~ $0.01/h) with an 8GiB EBS Volume (~ $0.03/day) !!
  !! You should delete the stack when you are done !!
  !! This is designed for learning purpose (use a sandbox or a dev account) !!
  !! YOU SHOULD NOT USE A PRODUCTION ACCOUNT FOR TESTING !!
  
# Template readme :
# The latest AMI ID is stored in aws systems manager (ssm) parameter store (public parameters)
# e.g.: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
# See all possible parameter values with the link provided in the stack outputs 
# if you do not see them, create at least one parameter in parameter store

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  InstanceType:
    Type: String
    Default: t3.nano

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: LatestAmiId
      InstanceType:
        Ref: InstanceType
      Tags:
        - Key: Name
          Value: 
            Ref: AWS::StackName

Outputs:
  SSMPublicParametersUrl:
    Description: "Link to SSM public parameters possible values for the latest linux ami"
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/systems-manager/parameters/?region=${AWS::Region}&tab=PublicTable#public_parameter_service=ami-amazon-linux-latest"            